### ISSUE TITLE
Main definitions

### ISSUE THREAD

**Issue by andreybs11** [hulilabs/ju-components#15]
Create a reusable and extendable way to store common definitions like blocks (ie. ComponentDef)

**Comment by andreybs11** [comment]
**Future improvements:**
- Distinguish between public and custom components of a project
- Tool for public components installation (ju-catalog repo and versioning) 
- Dynamically generate a playground/sandbox
- CSS resource handling

**Comment by jpgarbanzo** [comment]
Pull request merged and issue closed.

Thanks @andreybs11 !
